# Generated by Django 3.0.6 on 2020-05-15 22:00

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0005_auto_20200513_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
