# Generated by Django 3.0.6 on 2020-05-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0007_house_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
