# Generated by Django 3.0.6 on 2020-05-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0008_auto_20200516_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='floor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='m2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='room',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
