# Generated by Django 3.0.6 on 2020-05-19 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0013_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='level',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='tree_id',
        ),
    ]
