# Generated by Django 3.0.6 on 2020-05-21 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0016_auto_20200520_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
